<?php

namespace AppBundle\Repository;

/**
 * ServiceAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceAccountRepository extends \Doctrine\ORM\EntityRepository
{
}
