<?php

namespace AppBundle\Repository;

/**
 * CapchaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapchaRepository extends \Doctrine\ORM\EntityRepository
{
}
