<?php

namespace AppBundle\Repository;

/**
 * FakeUserPoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FakeUserPoolRepository extends \Doctrine\ORM\EntityRepository
{
}
