<?php

namespace AppBundle\Repository;

/**
 * FakeBlogPoolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FakeBlogPoolRepository extends \Doctrine\ORM\EntityRepository
{
}
